### POST request to create a booking
POST http://localhost:3000/api/v1/bookings
Content-Type: application/json

{
  "userId": "696a511aea4207025673111d",
  "roomId": "696d308919af9c89e0939b38",
  "checkInDate": "2026-06-15",
  "checkOutDate": "2026-06-17"
}

### GET request to read all Bookings
GET http://localhost:3000/api/v1/bookings

### GET request to read a specific booking
GET http://localhost:3000/api/v1/bookings/BK-750444

### DELETE request to delete a user
DELETE http://localhost:3000/api/v1/bookings/BK-623170

### PATCH update a user
PATCH http://localhost:3000/api/v1/bookings/BK-750444
Content-Type: application/json

{
  "status": "confirmed"
}

### GET user booking
GET http://localhost:3000/api/v1/bookings/my-bookings