### POST request to create a booking
POST http://localhost:3000/api/v1/bookings
Content-Type: application/json

{
  "userId": "696fbc3a4833b6985ab42f09",
  "roomId": "696d306f19af9c89e0939b36",
  "checkInDate": "2025-11-13",
  "checkOutDate": "2025-11-15",
  "firstname": "Bogo",
  "lastname": "BOZO",
  "email": "bobo@Geemail.coom",
  "phone": "0969696969"
}

### GET request to read all Bookings
GET http://localhost:3000/api/v1/bookings

### GET request to read a specific booking
GET http://localhost:3000/api/v1/bookings/BK-286383

### DELETE request to delete a booking
DELETE http://localhost:3000/api/v1/bookings/BK-982768

### PATCH update a booking
PATCH http://localhost:3000/api/v1/bookings/BK-675378
Content-Type: application/json

{
  "status": "cancelled"
}

### GET user booking
GET http://localhost:3000/api/v1/bookings/my-bookings